name: CI - Unit Tests

on:
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.2']  # Define the PHP versions you want to test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}  # Use the PHP version from the matrix
          extensions: mbstring, intl, pcntl, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml --testdox --testsuite "Unit Tests"
